name: octodns-sync
run-name: OctoDNS Sync for ${{ github.event_name }} event on ${{ github.ref_name }} branch by ${{ github.actor }}
concurrency:
  group: octodns-sync
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GrantBirki/json-yaml-validate@v2.7.1
        with:
          comment: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run OctoDNS Sync - Dry Run
        uses: solvaholic/octodns-sync@main
        with:
          add_pr_comment: true
          pr_comment_token: ${{ secrets.GITHUB_TOKEN }}
          config_path: config/production.yaml
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Run OctoDNS Sync - Doit
        uses: solvaholic/octodns-sync@main
        if: github.event_name != 'pull_request'
        with:
          config_path: config/production.yaml
          doit: '--doit'
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}